# Generated by Django 5.0.6 on 2024-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family_photos/')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PortraitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portrait_photos/')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PregnantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pregnant_photos/')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-type', 'order'],
            },
        ),
    ]
