# Generated by Django 5.0.6 on 2024-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_portraitphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portraitphoto',
            options={'ordering': ['type', 'order']},
        ),
        migrations.AddField(
            model_name='portraitphoto',
            name='type',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1),
        ),
    ]
