# Generated by Django 5.0.6 on 2024-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_portraitphoto_options_portraitphoto_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family_photos/')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PregnantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pregnant_photos/')),
                ('description', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-type', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='portraitphoto',
            options={'ordering': ['-type', 'order']},
        ),
    ]
